In [5]:
import math
def basic_sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [7]:
basic_sigmoid(4)

0.9820137900379085

In [9]:
x=[1,2,3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [15]:
import numpy as np
x=np.array([1,2,4])
print(np.exp(x))
print(x+3)

[ 2.71828183  7.3890561  54.59815003]
[4 5 7]


In [17]:
np.exp?


Signature:       np.exp(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'exp'>
File:            c:\users\amrut\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the exponential of all elements in the input array.

Parameters
----------
x : array_like
    Input values.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
 

In [23]:
def sigmoid(x):
    s=1/(1+np.exp(-x))
    return s

In [25]:
x=np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [37]:
def sigmoid_grad(x):
    s=1/(1+np.exp(-x))
    res=s*(1-s)
    return res

In [39]:
x=np.array([1,2,3])
sigmoid_grad(x)

array([0.19661193, 0.10499359, 0.04517666])

## Reshaping

In [65]:
def image2vector(image):
    v=image.reshape((image.shape[0]*image.shape[1]*image.shape[2]),1)
    return v
    

In [67]:
image=np.array([[[0.67826139,0.2920281],
                 [0.90714982,0.528356347],
                 [0.4215251,0.45017551]],
                [[0.92814,0.9667764],
                 [0.83849,0.87467892],
                 [0.87539,0.12232]],
                [[0.372331,0.875381],
                 [0.21325,0.31143223],
                 [0.1123243,0.8718152]]])
image2vector(image)

array([[0.67826139],
       [0.2920281 ],
       [0.90714982],
       [0.52835635],
       [0.4215251 ],
       [0.45017551],
       [0.92814   ],
       [0.9667764 ],
       [0.83849   ],
       [0.87467892],
       [0.87539   ],
       [0.12232   ],
       [0.372331  ],
       [0.875381  ],
       [0.21325   ],
       [0.31143223],
       [0.1123243 ],
       [0.8718152 ]])

In [79]:
def normalization(y):
    x_norm=np.linalg.norm(x,axis=1,keepdims=True)
    y=y/x_norm
    return y
    

In [81]:
x=np.array([
    [0,1000,4],
    [2,6,4]])
normalization(x)

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

## Softmax function

In [99]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp,axis=1,keepdims=True)
    s=x_exp/x_sum
    return s

In [101]:
x=np.array([[1,2,3],[2,3,4]])
softmax(x)

array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])

## Vectoization

In [106]:
import time

s1=[0,2,3,4,5,6,8,9,4]
s2=[1,2,3,4,6,8,9,2,6]

t=time.process_time()
dot=0
for i in range(len(s1)):
    dot+=s1[i]*s2[i]
t1=time.process_time()    
print(dot)
print(t1-t)

221
0.0
